services:
  web:
    image: nginx:1.21-alpine
    read_only: true
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./conf/http.conf:/etc/nginx/conf.d/http.conf:ro
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx_cache:/var/cache/nginx
      - ./nginx_pid:/var/run
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
#      - NGINX_HOST=nginx.local.com
