version: '3.2'

services:
  web:
    image: nginx:1.21-alpine
    volumes:
      - ./html:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
#      - NGINX_HOST=nginx.local.com
